quotes = ["We're doomed!",
          "This is all your fault.",
          "This is madness!",
          "Sir, the possibility of successare approximately 3,720 to 1.",
          "I can assure you they will never get me onto one of those dreadful starships.",
          "In the event I don't make it back, I want you to know you've been a real friend, R2.",
          "I beg your pardon, but what do you mean, `naked?' My parts are showing?",
          "I am not sure this floor is entirely stable.",
          "Oh my goodness! Shut me down. Machines building machines. How   perverse.",
          "I'm programmed for etiquette, not destruction!",
          "Listen to them! They're dying, R2! Curse my metal body!",
          "Help! I think I'm melting! This is all your fault!",
          "You must repair him!",
          "Sir, if any of my circuits or gears will help,I'll donate them.",
          "No, I don't think he likes you at all. No, I don't like you either.",
          "We seem to be made to suffer. It's our lot in life.",
          "He made a fair move. Screaming about it can't help you.",
          "That malfunctioning little twerp, this is all his fault.",
          "You watch your language!",
          "My joints are freezing up.",
          "I thought that hairy beast would be the end of me.",
          "Just open the door, you stupid lug!"]